services:
  app:
    build: .
    container_name: kahvikamera
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: build.py
        - action: rebuild
          path: static
        - action: rebuild
          path: templates
        - action: rebuild
          path: requirements.txt
    ports:
      - "5000:8080"
